#' Get summary measures of the importance samples
#'
#' Given the importance samples calculate the maximum likelihood and the
#' variance using bootstrap procedures
#'
#' @param isamples The importance samples generated by is2
#' @param se_boot The number of bootstrap iterations to run
#'
#' @return A list containing the max likelihood and variance using bootstrap
#'
#' @export
summarise <- function(isamples, se_boot = 10000) {
  isamples <- unlist(isamples)
  max_lw <- max(isamples)
  n_samples <- length(isamples)
  # takes off the max and gets mean (avoids infs)
  mean_centred_lw <- mean(exp(isamples - max_lw))
  lw <- log(mean_centred_lw) + max_lw # puts max back on to get the lw

  ##### bootstrapping for SE ######
  log_marglik_boot <- array(dim = se_boot)
  for (i in 1:se_boot) {
    # resample with replacement from the lw
    log_weight_boot <- sample(isamples, n_samples, replace = TRUE)
    max_boot <- max(log_weight_boot)
    # takes off the max and gets mean (avoids infs)
    centred_boot <- mean(exp(log_weight_boot - max_boot))
    log_marglik_boot[i] <- log(centred_boot) + max_boot # puts max back on
  }
  list(
    maximum_likelihood = lw,
    variance = stats::var(log_marglik_boot)
  )
}
